// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: pb/order_item.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=UnitPrice,proto3" json:"UnitPrice,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,5,opt,name=TotalPrice,proto3" json:"TotalPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_pb_order_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderItem) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type CreateOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItem     *OrderItem             `protobuf:"bytes,1,opt,name=orderItem,proto3" json:"orderItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderItemRequest) Reset() {
	*x = CreateOrderItemRequest{}
	mi := &file_pb_order_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItemRequest) ProtoMessage() {}

func (x *CreateOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItemRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderItemRequest) GetOrderItem() *OrderItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

type CreateOrderItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItem     *OrderItem             `protobuf:"bytes,1,opt,name=orderItem,proto3" json:"orderItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderItemResponse) Reset() {
	*x = CreateOrderItemResponse{}
	mi := &file_pb_order_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItemResponse) ProtoMessage() {}

func (x *CreateOrderItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItemResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderItemResponse) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderItemResponse) GetOrderItem() *OrderItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

type GetAllOrderItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrderItemsRequest) Reset() {
	*x = GetAllOrderItemsRequest{}
	mi := &file_pb_order_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrderItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrderItemsRequest) ProtoMessage() {}

func (x *GetAllOrderItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrderItemsRequest.ProtoReflect.Descriptor instead.
func (*GetAllOrderItemsRequest) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{3}
}

type GetAllOrderItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItems    []*OrderItem           `protobuf:"bytes,1,rep,name=orderItems,proto3" json:"orderItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrderItemsResponse) Reset() {
	*x = GetAllOrderItemsResponse{}
	mi := &file_pb_order_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrderItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrderItemsResponse) ProtoMessage() {}

func (x *GetAllOrderItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrderItemsResponse.ProtoReflect.Descriptor instead.
func (*GetAllOrderItemsResponse) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllOrderItemsResponse) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

type GetOrderItemsByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderItemsByIdRequest) Reset() {
	*x = GetOrderItemsByIdRequest{}
	mi := &file_pb_order_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderItemsByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderItemsByIdRequest) ProtoMessage() {}

func (x *GetOrderItemsByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderItemsByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrderItemsByIdRequest) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderItemsByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderItemByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItem     *OrderItem             `protobuf:"bytes,1,opt,name=orderItem,proto3" json:"orderItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderItemByIdResponse) Reset() {
	*x = GetOrderItemByIdResponse{}
	mi := &file_pb_order_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderItemByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderItemByIdResponse) ProtoMessage() {}

func (x *GetOrderItemByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderItemByIdResponse.ProtoReflect.Descriptor instead.
func (*GetOrderItemByIdResponse) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderItemByIdResponse) GetOrderItem() *OrderItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

type UpdateOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItem     *OrderItem             `protobuf:"bytes,1,opt,name=orderItem,proto3" json:"orderItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderItemRequest) Reset() {
	*x = UpdateOrderItemRequest{}
	mi := &file_pb_order_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderItemRequest) ProtoMessage() {}

func (x *UpdateOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrderItemRequest) GetOrderItem() *OrderItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

type UpdateOrderItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItem     *OrderItem             `protobuf:"bytes,1,opt,name=orderItem,proto3" json:"orderItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderItemResponse) Reset() {
	*x = UpdateOrderItemResponse{}
	mi := &file_pb_order_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderItemResponse) ProtoMessage() {}

func (x *UpdateOrderItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderItemResponse) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOrderItemResponse) GetOrderItem() *OrderItem {
	if x != nil {
		return x.OrderItem
	}
	return nil
}

type DeleteOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderItemRequest) Reset() {
	*x = DeleteOrderItemRequest{}
	mi := &file_pb_order_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderItemRequest) ProtoMessage() {}

func (x *DeleteOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteOrderItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOrderItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderItemResponse) Reset() {
	*x = DeleteOrderItemResponse{}
	mi := &file_pb_order_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderItemResponse) ProtoMessage() {}

func (x *DeleteOrderItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_order_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrderItemResponse) Descriptor() ([]byte, []int) {
	return file_pb_order_item_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteOrderItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pb_order_item_proto protoreflect.FileDescriptor

var file_pb_order_item_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x9d, 0x01, 0x0a,
	0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1c,
	0x0a, 0x09, 0x55, 0x6e, 0x69, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x55, 0x6e, 0x69, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x48, 0x0a, 0x16,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x49, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65,
	0x6d, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2a, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74,
	0x65, 0x6d, 0x22, 0x48, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x09,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x49, 0x0a, 0x17,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x33, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xab, 0x03, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1f,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x50, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x1d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x6c, 0x65, 0x73, 0x2d, 0x7a, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pb_order_item_proto_rawDescOnce sync.Once
	file_pb_order_item_proto_rawDescData []byte
)

func file_pb_order_item_proto_rawDescGZIP() []byte {
	file_pb_order_item_proto_rawDescOnce.Do(func() {
		file_pb_order_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_order_item_proto_rawDesc), len(file_pb_order_item_proto_rawDesc)))
	})
	return file_pb_order_item_proto_rawDescData
}

var file_pb_order_item_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pb_order_item_proto_goTypes = []any{
	(*OrderItem)(nil),                // 0: order.OrderItem
	(*CreateOrderItemRequest)(nil),   // 1: order.CreateOrderItemRequest
	(*CreateOrderItemResponse)(nil),  // 2: order.CreateOrderItemResponse
	(*GetAllOrderItemsRequest)(nil),  // 3: order.GetAllOrderItemsRequest
	(*GetAllOrderItemsResponse)(nil), // 4: order.GetAllOrderItemsResponse
	(*GetOrderItemsByIdRequest)(nil), // 5: order.GetOrderItemsByIdRequest
	(*GetOrderItemByIdResponse)(nil), // 6: order.GetOrderItemByIdResponse
	(*UpdateOrderItemRequest)(nil),   // 7: order.UpdateOrderItemRequest
	(*UpdateOrderItemResponse)(nil),  // 8: order.UpdateOrderItemResponse
	(*DeleteOrderItemRequest)(nil),   // 9: order.DeleteOrderItemRequest
	(*DeleteOrderItemResponse)(nil),  // 10: order.DeleteOrderItemResponse
}
var file_pb_order_item_proto_depIdxs = []int32{
	0,  // 0: order.CreateOrderItemRequest.orderItem:type_name -> order.OrderItem
	0,  // 1: order.CreateOrderItemResponse.orderItem:type_name -> order.OrderItem
	0,  // 2: order.GetAllOrderItemsResponse.orderItems:type_name -> order.OrderItem
	0,  // 3: order.GetOrderItemByIdResponse.orderItem:type_name -> order.OrderItem
	0,  // 4: order.UpdateOrderItemRequest.orderItem:type_name -> order.OrderItem
	0,  // 5: order.UpdateOrderItemResponse.orderItem:type_name -> order.OrderItem
	1,  // 6: order.OrderItemService.CreateOrderItem:input_type -> order.CreateOrderItemRequest
	3,  // 7: order.OrderItemService.Request:input_type -> order.GetAllOrderItemsRequest
	5,  // 8: order.OrderItemService.GetOrderItemsById:input_type -> order.GetOrderItemsByIdRequest
	7,  // 9: order.OrderItemService.UpdateOrderItem:input_type -> order.UpdateOrderItemRequest
	9,  // 10: order.OrderItemService.DeleteOrderItem:input_type -> order.DeleteOrderItemRequest
	2,  // 11: order.OrderItemService.CreateOrderItem:output_type -> order.CreateOrderItemResponse
	4,  // 12: order.OrderItemService.Request:output_type -> order.GetAllOrderItemsResponse
	6,  // 13: order.OrderItemService.GetOrderItemsById:output_type -> order.GetOrderItemByIdResponse
	8,  // 14: order.OrderItemService.UpdateOrderItem:output_type -> order.UpdateOrderItemResponse
	10, // 15: order.OrderItemService.DeleteOrderItem:output_type -> order.DeleteOrderItemResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pb_order_item_proto_init() }
func file_pb_order_item_proto_init() {
	if File_pb_order_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_order_item_proto_rawDesc), len(file_pb_order_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_order_item_proto_goTypes,
		DependencyIndexes: file_pb_order_item_proto_depIdxs,
		MessageInfos:      file_pb_order_item_proto_msgTypes,
	}.Build()
	File_pb_order_item_proto = out.File
	file_pb_order_item_proto_goTypes = nil
	file_pb_order_item_proto_depIdxs = nil
}
